apiVersion: v1
kind: Pod
metadata:
  name: probe
spec:
  containers:
  - name: uygulama
    image: quay.io/oktaysavdi/probe
    readinessProbe:
      httpGet:
        path: /health/ready
        port: 80
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 15
    livenessProbe:
      initialDelaySeconds: 2
      periodSeconds: 5
      httpGet:
        path: /health/live
        port: 80
        scheme: HTTP
